// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restoran.DAL;

#nullable disable

namespace Restoran.DAL.Migrations
{
    [DbContext(typeof(RestoranContext))]
    [Migration("20251211103059_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Restoran.DAL.Entities.Gost", b =>
                {
                    b.Property<int>("IDGosta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImeGosta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrezimeGosta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.HasKey("IDGosta");

                    b.ToTable("Gost", (string)null);
                });

            modelBuilder.Entity("Restoran.DAL.Entities.Rezervacija", b =>
                {
                    b.Property<int>("IDRezervacije")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojOsoba")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("IDGosta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDStola")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Vreme")
                        .HasColumnType("TEXT");

                    b.HasKey("IDRezervacije");

                    b.HasIndex("IDGosta");

                    b.HasIndex("IDStola");

                    b.ToTable("Rezervacija", (string)null);
                });

            modelBuilder.Entity("Restoran.DAL.Entities.Sto", b =>
                {
                    b.Property<int>("IDStola")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojMesta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojStola")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lokacija")
                        .HasColumnType("TEXT");

                    b.HasKey("IDStola");

                    b.ToTable("Sto", (string)null);
                });

            modelBuilder.Entity("Restoran.DAL.Entities.Rezervacija", b =>
                {
                    b.HasOne("Restoran.DAL.Entities.Gost", "Gost")
                        .WithMany("Rezervacije")
                        .HasForeignKey("IDGosta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restoran.DAL.Entities.Sto", "Sto")
                        .WithMany("Rezervacije")
                        .HasForeignKey("IDStola")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gost");

                    b.Navigation("Sto");
                });

            modelBuilder.Entity("Restoran.DAL.Entities.Gost", b =>
                {
                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("Restoran.DAL.Entities.Sto", b =>
                {
                    b.Navigation("Rezervacije");
                });
#pragma warning restore 612, 618
        }
    }
}
